[package]
name = "fontconfig-parser"
version = "0.1.1"
edition = "2018"
license = "MIT"
documentation = "https://docs.rs/fontconfig-parser"
description = "fontconfig file parser in pure Rust"
repository = "https://github.com/Riey/fontconfig-parser"
homepage = "https://github.com/Riey/fontconfig-parser"
readme = "README.md"
categories = ["parser-implementations", "no-std"]
keywords = ["fontconfig"]

[features]
default = ["std", "roxmltree/std"]
std = []

[dependencies]
roxmltree = { version = "0.14.1", default-features = false }

[dev-dependencies]
criterion = "0.3.5"
k9 = "0.11.1"

[[bench]]
name = "parse_test_conf"
harness = false

[profile.bench]
lto = "thin"

[profile.release]
lto = "thin"
