[package]
name = "fontconfig-types"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-kinds = "0.5.1"
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.30"

[dev-dependencies]
quick-xml = { version = "0.22.0", default-features = false, features = ["serialize"] }
