[package]
name = "fontconfig-parser"
version = "0.1.0"
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = { version = "0.22.0", default-features = false }
strum = "0.22.0"
strum_macros = "0.22.0"
thiserror = "1.0.30"

[dev-dependencies]
regex = "1.5.4"
