[package]
name = "fontconfig-parser"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
xmlparser = "0.13.3"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "parse_test_conf"
harness = false

[profile.bench]
lto = "thin"

[profile.release]
lto = "thin"
